services:
  - type: web
    name: interior-by-ode
    runtime: node
    buildCommand: cd server && npm install
    plan: free
    startCommand: cd server && npm run deploy
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        fromDatabase:
          name: interiors_db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://interior-by-ode.onrender.com
    healthCheckPath: /
    autoDeploy: true
    preDeployCommand: |
      psql $DATABASE_URL -c 'CREATE TABLE IF NOT EXISTS "session" ("sid" varchar NOT NULL COLLATE "default","sess" json NOT NULL,"expire" timestamp(6) NOT NULL) WITH (OIDS=FALSE);' -c 'ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;'


databases:
  - name: interiors_db
    databaseName: interiors_db
    user: interiors_user
    plan: free
